#!/bin/sh
#
# Init buttons and LEDs...
#

case "$1" in
  start)

  /root/all_LEDs_init.sh
  /root/init_buttons.sh

  echo "OK"
        ;;
  stop)

        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
