echo 0 > /sys/class/gpio/gpio140/value
echo 1 > /sys/class/gpio/gpio166/value
echo 1 > /sys/class/gpio/gpio36/value
echo 1 > /sys/class/gpio/gpio192/value
echo 1 > /sys/class/gpio/gpio150/value
echo 1 > /sys/class/gpio/gpio37/value
echo 1 > /sys/class/gpio/gpio144/value
echo 1 > /sys/class/gpio/gpio145/value
echo 1 > /sys/class/gpio/gpio128/value
echo 1 > /sys/class/gpio/gpio133/value
echo 1 > /sys/class/gpio/gpio33/value
echo 1 > /sys/class/gpio/gpio129/value
echo 1 > /sys/class/gpio/gpio32/value
echo 1 > /sys/class/gpio/gpio130/value
echo 1 > /sys/class/gpio/gpio131/value
echo 1 > /sys/class/gpio/gpio132/value
echo 1 > /sys/class/gpio/gpio135/value
echo 1 > /sys/class/gpio/gpio134/value
echo 1 > /sys/class/gpio/gpio137/value
echo 1 > /sys/class/gpio/gpio136/value
echo 1 > /sys/class/gpio/gpio195/value
echo 1 > /sys/class/gpio/gpio138/value
echo 1 > /sys/class/gpio/gpio196/value
echo 1 > /sys/class/gpio/gpio143/value
